/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package victor;

import consultas.MySqlConn;
import consultas.baseDeDatos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    
    Toolkit tk;
    Dimension d;
    int ancho,alto;
    MySqlConn conn;
    
    public CheckIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoHab = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidoP = new javax.swing.JLabel();
        jLabelApellidoM = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelIngreso = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jLabelNoHabitacion = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidoP = new javax.swing.JTextField();
        jTextFieldApellidoM = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jDateChooserIngreso = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerDias = new javax.swing.JSpinner();
        jSpinnerHuespedes = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonHabSencilla = new javax.swing.JRadioButton();
        jRadioButtonHabDoble = new javax.swing.JRadioButton();
        jRadioButtonHabTriple = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNoHab = new javax.swing.JList();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check-In");
        setExtendedState(4);
        setMinimumSize(new java.awt.Dimension(1, 1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new Dimension(ancho,alto));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabelNombre.setText("Nombre:");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabelApellidoP.setText("Apellido Paterno:");
        jPanel1.add(jLabelApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabelApellidoM.setText("Apellido Materno:");
        jPanel1.add(jLabelApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabelCiudad.setText("Ciudad:");
        jPanel1.add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 153, -1, -1));

        jLabelIngreso.setText("Ingreso:");
        jPanel1.add(jLabelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 182, -1, -1));

        jLabelDias.setText("Dias de hospedaje:");
        jPanel1.add(jLabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 208, -1, -1));

        jLabelNoHabitacion.setText("Número de habitación:");
        jPanel1.add(jLabelNoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, -1));
        jPanel1.add(jTextFieldApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));
        jPanel1.add(jTextFieldApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));
        jPanel1.add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, -1));
        jPanel1.add(jDateChooserIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, -1));

        jLabel1.setText("Tipo de habitación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        jPanel1.add(jSpinnerDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 50, -1));
        jPanel1.add(jSpinnerHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 50, -1));

        jLabel2.setText("Cantidad de huéspedes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        buttonGroupTipoHab.add(jRadioButtonHabSencilla);
        jRadioButtonHabSencilla.setSelected(true);
        jRadioButtonHabSencilla.setText("Sencilla");
        jPanel1.add(jRadioButtonHabSencilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        buttonGroupTipoHab.add(jRadioButtonHabDoble);
        jRadioButtonHabDoble.setText("Doble");
        jPanel1.add(jRadioButtonHabDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        buttonGroupTipoHab.add(jRadioButtonHabTriple);
        jRadioButtonHabTriple.setText("Triple");
        jPanel1.add(jRadioButtonHabTriple, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jListNoHab.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310", "311", "312", "313", "314", "315" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListNoHab);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 70, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCheckIn.jpg"))); // NOI18N
        jLabelFondo.setPreferredSize(jPanel1.getPreferredSize());
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        String datos[] = new String[9];
        /*
        [1] - Nombre
        [2] - Apellido Paterno
        [3] - Apellido Materno
        [4] - Ciudad
        [5] - Fecha de ingreso
        [6] - Fecha de salida
        [7] - Número de habitación
        [8] - Número de personas que se van a hospedar (validado)
        */
        try{
            
            Calendar ingreso = this.jDateChooserIngreso.getCalendar();
            String salida, aux, tipo = null;
            int hab;
            boolean registroPermitido = true;
            SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
            
            //LLenado de valores [1], [2], [3], [4], [5]
            datos[1] = this.jTextFieldNombre.getText().trim();
            datos[2] = this.jTextFieldApellidoP.getText().trim();
            datos[3] = this.jTextFieldApellidoM.getText().trim();
            datos[4] = this.jTextFieldCiudad.getText().trim();
            datos[5] = formatofecha.format(this.jDateChooserIngreso.getDate());
            
            //Suma de fecha con dias de hospedaje [6]
            aux = this.jSpinnerDias.getValue().toString();
            int dias = Integer.parseInt(aux);
            if(dias <= 0){
                JOptionPane.showMessageDialog(this, "Número de dias para hospedaje no válido");
                registroPermitido = false;
            }
            ingreso.add(Calendar.DATE, dias);
            int dia = ingreso.get(Calendar.DATE);
            int mes = ingreso.get(Calendar.MONTH)+1;
            int año = ingreso.get(Calendar.YEAR);
            String dd, MM, yyyy;
            if (dia < 10){
                dd = "0"+ dia;
            }else{
                dd = Integer.toString(dia);
            }
            if (mes < 10){
                MM = "0" + mes;
            }else{
                MM = Integer.toString(mes);
            }
            yyyy = Integer.toString(año);
            salida = yyyy + "-" + MM + "-" + dd;
            datos[6] = salida;
            
            // LLenado de valores [7], [8]
            datos[7] = (String) this.jListNoHab.getSelectedValue();
            datos[8] = (String) this.jSpinnerHuespedes.getValue().toString();
            int aux3 = Integer.parseInt(datos[8]);
            if(aux3 <= 0){
                JOptionPane.showMessageDialog(this, "Número de huéspedes no válido");
                registroPermitido = false;
            }
            
            //Asignación de tipo de habitación por No. de habitación
            /*
                Cantidad de personas
                Sencilla 1 - 3
                Doble    2 - 4
                Triple   3 - 5
            */
            
            int aux2 = Integer.parseInt(datos[7]);
            if (aux2 >= 101 && aux2 <= 105 || aux2 >= 201 && aux2 <= 203 || aux2 >= 301 && aux2 <= 306){
                this.jRadioButtonHabSencilla.setSelected(true);
            }
            if (aux2 >= 106 && aux2 <= 111 || aux2 >= 204 && aux2 <= 210 || aux2 >= 307 && aux2 <= 309){
                this.jRadioButtonHabDoble.setSelected(true);
            }
            if (aux2 >= 112 && aux2 <= 115 || aux2 >= 211 && aux2 <= 215 || aux2 >= 310 && aux2 <= 315){
                this.jRadioButtonHabTriple.setSelected(true);
            }
            
            if (this.jRadioButtonHabSencilla.isSelected()){
                tipo = "Sencilla";
                if (aux3 < 0 && aux3 > 3){
                    registroPermitido = false;
                }
            }
            if (this.jRadioButtonHabDoble.isSelected()){
                tipo = "Doble";
                if (aux3 < 0 && aux3 > 4){
                    registroPermitido = false;
                }
            }
            if (this.jRadioButtonHabTriple.isSelected()){
                tipo = "Triple";
                if (aux3 < 0 && aux3 > 5){
                    registroPermitido = false;
                }
            }
            
            
            //Impresión de datos en consola (Solo para pruebas)
            System.out.println("-----------------------");
            for (int i = 0; i < datos.length; i++) {
                System.out.println(datos[i]);
            }
            System.out.println(tipo);
            
            if (registroPermitido){
                baseDeDatos b = new baseDeDatos();
                try{
                    b.registrarHuesped(datos);
                    JOptionPane.showMessageDialog(this,"Huésped ingresado con éxito");
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this,"Error al ingresar el huésped");
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error en el registro");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoHab;
    private javax.swing.JButton jButtonRegistrar;
    private com.toedter.calendar.JDateChooser jDateChooserIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellidoM;
    private javax.swing.JLabel jLabelApellidoP;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelNoHabitacion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JList jListNoHab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonHabDoble;
    private javax.swing.JRadioButton jRadioButtonHabSencilla;
    private javax.swing.JRadioButton jRadioButtonHabTriple;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JSpinner jSpinnerHuespedes;
    private javax.swing.JTextField jTextFieldApellidoM;
    private javax.swing.JTextField jTextFieldApellidoP;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
